# -*- coding: utf-8 -*-
"""ASSIGNMENT 3 task1:.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q8fghR4MK8vfcXBPT_DgdjYFum9Umpda
"""

def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

# Sample call
number = 5
print("Factorial of", number, "is:", factorial(number))