# -*- coding: utf-8 -*-
"""ASSIGNMENT 3 task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PUYo9vMGsCWnW3pACHTQvtfhJoqhMBdp
"""

import math

# Ask the user for input
num = float(input("Enter a number: "))

# Perform calculations using math module
sqrt_val = math.sqrt(num)
log_val = math.log(num)         # natural log (base e)
sine_val = math.sin(num)        # input should be in radians

# Display results
print("Square root of", num, "is:", sqrt_val)
print("Natural logarithm of", num, "is:", log_val)
print("Sine of", num, "(in radians) is:", sine_val)